const PP_LEVELS=['Desenv. Inicial','Desenv. Básico','Desenv. Adequado','Domínio Proficiente','Domínio Avançado'];
const state={pp1:[],pp2:[],pp3:[],detalhado:[],resumo:[],auditoria:[]};
function qs(s){return document.querySelector(s)}
function qsa(s){return Array.from(document.querySelectorAll(s))}
function showMessage(text,type='info'){const msg=qs('#msg');if(msg){msg.textContent=text;msg.dataset.type=type}}
function totalFiles(){return state.pp1.length+state.pp2.length+state.pp3.length}
function formatSize(bytes){if(!bytes)return '0 KB';return bytes<1048576?Math.round(bytes/1024)+' KB':(bytes/1048576).toFixed(1)+' MB'}
function norm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}
function key(v){return norm(v).toUpperCase().replace(/[^A-Z0-9]/g,'')}
function parseNum(v){if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace('%','').replace(',','.').trim());return Number.isFinite(n)?n:null}
function esc(v){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function detectTurma(name){const base=(name||'').replace(/\.[^.]+$/,'').toUpperCase();const m=base.match(/\b([1-9][A-Z]|[1-9]\s*[A-Z]|[1-3][A-Z]\s*(EM|PC|EF)?)\b/);return m?m[0].replace(/\s+/g,' '):''}
function getCell(row,names){const ks=Object.keys(row||{});const map=Object.fromEntries(ks.map(k=>[key(k),k]));for(const n of names){const f=map[key(n)];if(f)return row[f]}return ''}
function nivelPP(status,aeq){const st=norm(status).toUpperCase();const ae=parseNum(aeq);if(st.includes('ABAIXO'))return ae!==null&&ae<=-2?'Desenv. Inicial':'Desenv. Básico';if(st.includes('BASICO'))return ae!==null&&ae<0?'Desenv. Básico':'Desenv. Adequado';if(st.includes('ADEQUADO')||st.includes('PROFICIENTE'))return ae!==null&&ae>=1?'Domínio Proficiente':'Desenv. Adequado';if(st.includes('AVANCADO'))return 'Domínio Avançado';return '—'}
function loadScript(src,globalName){return new Promise((resolve,reject)=>{if(globalName&&window[globalName])return resolve(window[globalName]);const s=document.createElement('script');s.src=src;s.onload=()=>resolve(globalName?window[globalName]:true);s.onerror=()=>reject(new Error('Falha ao carregar '+src));document.head.appendChild(s)})}
function loadXLSX(){return loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js','XLSX')}
function loadJSZip(){return loadScript('https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js','JSZip')}
function parseCsv(txt){const sep=txt.includes(';')?';':',';const lines=txt.split(/\r?\n/).filter(l=>l.trim());const headers=(lines.shift()||'').split(sep).map(h=>h.trim());return lines.map(line=>Object.fromEntries(line.split(sep).map((v,i)=>[headers[i]||('Coluna '+(i+1)),v.trim()]))) }
async function readWorkbookRows(buffer,sourceName){const XLSX=await loadXLSX();const wb=XLSX.read(buffer,{type:'array'});let rows=[];wb.SheetNames.forEach(sheet=>{const json=XLSX.utils.sheet_to_json(wb.Sheets[sheet],{defval:''});json.forEach(r=>rows.push({...r,ArquivoOrigem:sourceName,AbaOrigem:sheet}))});return rows}
async function readFileRows(file){
  const ext=(file.name.split('.').pop()||'').toLowerCase();
  if(ext==='csv')return parseCsv(await file.text()).map(r=>({...r,ArquivoOrigem:file.name}));
  if(ext==='xlsx'||ext==='xls')return readWorkbookRows(await file.arrayBuffer(),file.name);
  if(ext==='zip'){
    const JSZip=await loadJSZip();const zip=await JSZip.loadAsync(await file.arrayBuffer());let all=[];
    const entries=Object.values(zip.files).filter(z=>!z.dir&&!/^__MACOSX\//.test(z.name)&&!z.name.includes('/.~')&&!z.name.startsWith('.'));
    for(const entry of entries){const e=(entry.name.split('.').pop()||'').toLowerCase();try{if(e==='xlsx'||e==='xls'){const buf=await entry.async('arraybuffer');const rows=await readWorkbookRows(buf,entry.name);all=all.concat(rows.map(r=>({...r,ZipOrigem:file.name})))}else if(e==='csv'){const txt=await entry.async('text');all=all.concat(parseCsv(txt).map(r=>({...r,ArquivoOrigem:entry.name,ZipOrigem:file.name})))}}catch(err){state.auditoria.push({Aba:'Auditoria_Export',Contexto:entry.name,Disciplina:'-',Tipo:'ERRO_LEITURA_ARQUIVO_ZIP',Detalhe:err.message,Valor:'—'})}}
    if(!all.length)state.auditoria.push({Aba:'Auditoria_Export',Contexto:file.name,Disciplina:'-',Tipo:'ZIP_SEM_PLANILHAS_LIDAS',Detalhe:'Nenhum xlsx/xls/csv encontrado ou legível',Valor:'—'});
    return all;
  }
  return [];
}
function rowToDetalhe(row,idx,grupo,fileName){const turma=getCell(row,['Turma','Classe','Ano/Série','Ano Serie','Série','Serie'])||detectTurma(fileName)||detectTurma(row.ArquivoOrigem)||'—';const estudante=getCell(row,['Estudante','Aluno','Nome','Nome do Aluno','Nome Aluno'])||('Registro '+(idx+1));const ra=getCell(row,['RA','Código','Codigo','ID','Cod Aluno'])||'—';const lpStatus=getCell(row,['LP Status','Status LP','Status Língua Portuguesa','Status Lingua Portuguesa','LP Nível','LP Nivel','Nivel LP']);const mtStatus=getCell(row,['MT Status','MAT Status','Status MT','Status MAT','Status Matemática','Status Matematica','MT Nível','MT Nivel','Nivel MT']);const lpAE=getCell(row,['LP Aprend. Equiv','LP Aprendizagem Equivalente','LP AE','Língua Portuguesa Aprend. Equiv']);const mtAE=getCell(row,['MT Aprend. Equiv','MAT Aprend. Equiv','MT Aprendizagem Equivalente','MAT Aprendizagem Equivalente','MT AE','MAT AE']);return {Avaliacao:grupo.toUpperCase(),Arquivo:fileName,Planilha:row.ArquivoOrigem||fileName,Turma:turma,Estudante:estudante,RA:ra,'LP Status':lpStatus||'—','LP Aprend. Equiv':lpAE||'—','LP Nível PP':nivelPP(lpStatus,lpAE),'MT Status':mtStatus||'—','MT Aprend. Equiv':mtAE||'—','MT Nível PP':nivelPP(mtStatus,mtAE)}}
async function buildDetalhado(){state.auditoria=[];const out=[];for(const grupo of ['pp1','pp2','pp3']){for(const file of state[grupo]){const rows=await readFileRows(file);rows.forEach((r,i)=>out.push(rowToDetalhe(r,i,grupo,file.name)))}}state.detalhado=out;return out}
function summarizeDetalhado(){const groups={};state.detalhado.forEach(r=>{const k=r.Avaliacao+'|'+r.Turma;if(!groups[k])groups[k]=[];groups[k].push(r)});state.resumo=Object.entries(groups).map(([k,rows])=>{const [avaliacao,turma]=k.split('|');const o={Avaliacao:avaliacao,Turma:turma,Total:rows.length,'LP Aprend. Média':'—','MT Aprend. Média':'—'};['LP','MT'].forEach(area=>{PP_LEVELS.forEach(level=>{const c=rows.filter(r=>r[area+' Nível PP']===level).length;o[area+' % '+level]=rows.length?Number((c*100/rows.length).toFixed(2)):0});const vals=rows.map(r=>parseNum(r[area+' Aprend. Equiv'])).filter(v=>v!==null);o[area+' Aprend. Média']=vals.length?Number((vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(2)):'—'});return o});return state.resumo}
function gerarAuditoriaExport(){const aud=state.auditoria.filter(a=>a.Tipo&&a.Tipo.startsWith('ERRO')||a.Tipo==='ZIP_SEM_PLANILHAS_LIDAS');state.resumo.forEach(r=>['LP','MT'].forEach(area=>{const vals=PP_LEVELS.map(l=>parseNum(r[area+' % '+l]));vals.forEach((v,i)=>{if(v===null)aud.push({Aba:'Resumo',Contexto:r.Avaliacao+' '+r.Turma,Disciplina:area,Tipo:'COLUNA_VAZIA_OU_AUSENTE',Detalhe:PP_LEVELS[i],Valor:'—'})});if(vals.every(v=>v!==null)){const sum=vals.reduce((a,b)=>a+b,0);if(Math.abs(sum-100)>1)aud.push({Aba:'Resumo',Contexto:r.Avaliacao+' '+r.Turma,Disciplina:area,Tipo:'SOMA_5_FAIXAS_DIFERENTE_DE_100',Detalhe:'Total',Valor:sum.toFixed(2)+'%'})}}));state.detalhado.forEach(r=>['LP','MT'].forEach(area=>{const n=r[area+' Nível PP'];if(!PP_LEVELS.includes(n)&&n!=='—')aud.push({Aba:'Detalhado',Contexto:r.Arquivo+' - '+r.Estudante,Disciplina:area,Tipo:'NIVEL_FORA_DAS_5_FAIXAS',Detalhe:n,Valor:n});if(n==='—')aud.push({Aba:'Detalhado',Contexto:r.Arquivo+' - '+r.Estudante,Disciplina:area,Tipo:'NIVEL_GRAVADO_COMO_TRACO',Detalhe:area+' Nível PP',Valor:'—'})}));if(!aud.length)aud.push({Aba:'Auditoria_Export',Contexto:'Exportação',Disciplina:'LP/MT',Tipo:'SEM_DIVERGENCIAS',Detalhe:'5 faixas conferidas',Valor:'OK'});state.auditoria=aud;return aud}
function updateButtons(){const total=totalFiles();qsa('button').forEach(btn=>{const txt=(btn.textContent||'').toLowerCase();if(txt.includes('analisar')){btn.disabled=total===0;btn.textContent='Analisar ('+total+')'}if(txt.includes('excel'))btn.disabled=total===0})}
function updateCards(){['pp1','pp2','pp3'].forEach((k,i)=>{const card=qsa('.upload-card')[i];if(!card)return;const count=state[k].length;const span=card.querySelector('.card-head span');if(span)span.textContent=count+' arquivo'+(count===1?'':'s');let list=card.querySelector('.file-list');if(!list){list=document.createElement('div');list.className='file-list';card.appendChild(list)}list.innerHTML=count?state[k].map(f=>'<div class="file-row"><span>'+esc(f.name)+'</span><small>'+formatSize(f.size)+'</small></div>').join(''):''})}
function updateMetrics(){const cards=qsa('.dashboard-preview article strong');if(cards[0])cards[0].textContent=state.detalhado.length||totalFiles();if(cards[1])cards[1].textContent=new Set(state.detalhado.map(r=>r.Turma).filter(Boolean)).size||new Set([...state.pp1,...state.pp2,...state.pp3].map(f=>detectTurma(f.name)).filter(Boolean)).size;if(cards[2])cards[2].textContent=state.detalhado.length?'OK':(totalFiles()?'Pronto':'0');if(cards[3])cards[3].textContent=state.auditoria.length}
function renderPreview(){let box=qs('.notice');if(!box)return;if(!state.detalhado.length){box.innerHTML='Envie arquivos <b>.ZIP</b> ou <b>.xlsx</b> em PP1, PP2 e/ou PP3 e clique em <b>Analisar</b>.';return}box.innerHTML='<b>'+state.detalhado.length+'</b> registro(s) analisado(s), <b>'+state.resumo.length+'</b> turma(s)/grupo(s), <b>'+state.auditoria.length+'</b> item(ns) na Auditoria_Export.'}
function updateAll(){updateCards();updateButtons();updateMetrics();renderPreview()}
function handleInput(input,index){const k=['pp1','pp2','pp3'][index];state[k]=Array.from(input.files||[]);state.detalhado=[];state.resumo=[];state.auditoria=[];updateAll();if(state[k].length)showMessage(state[k].length+' arquivo(s) carregado(s) em '+k.toUpperCase()+'.','success')}
async function analyze(){try{if(!totalFiles()){showMessage('Envie pelo menos um arquivo antes de analisar.','error');return}showMessage('Extraindo ZIP/planilhas e calculando Nível PP...');await buildDetalhado();summarizeDetalhado();gerarAuditoriaExport();updateAll();if(!state.detalhado.length){showMessage('Nenhum estudante encontrado. Verifique se o ZIP contém .xlsx/.xls/.csv e se as planilhas têm cabeçalho.','error');return}showMessage('Análise concluída: '+state.detalhado.length+' registro(s), '+state.resumo.length+' resumo(s), '+state.auditoria.length+' auditoria(s).','success')}catch(e){console.error(e);showMessage('Erro ao analisar: '+e.message,'error')}}
function makeSheet(XLSX,rows,headers){return XLSX.utils.json_to_sheet(rows,{header:headers})}
function widths(ws,arr){ws['!cols']=arr.map(w=>({wch:w}))}
async function exportSummary(){try{if(!totalFiles()){showMessage('Não há dados para exportar.','error');return}if(!state.detalhado.length){await analyze();if(!state.detalhado.length)return}const XLSX=await loadXLSX();const wb=XLSX.utils.book_new();const dh=['Avaliacao','Arquivo','Planilha','Turma','Estudante','RA','LP Status','LP Aprend. Equiv','LP Nível PP','MT Status','MT Aprend. Equiv','MT Nível PP'];const rh=['Avaliacao','Turma','Total','LP Aprend. Média',...PP_LEVELS.map(l=>'LP % '+l),'MT Aprend. Média',...PP_LEVELS.map(l=>'MT % '+l)];const ah=['Aba','Contexto','Disciplina','Tipo','Detalhe','Valor'];const wsD=makeSheet(XLSX,state.detalhado,dh);widths(wsD,[12,24,30,12,30,14,18,18,20,18,18,20]);const wsR=makeSheet(XLSX,state.resumo,rh);widths(wsR,[12,14,10,18,18,18,18,22,20,18,18,18,18,22,20]);const wsA=makeSheet(XLSX,state.auditoria,ah);widths(wsA,[18,44,12,34,30,18]);XLSX.utils.book_append_sheet(wb,wsD,'Detalhado');XLSX.utils.book_append_sheet(wb,wsR,'Resumo');XLSX.utils.book_append_sheet(wb,wsA,'Auditoria_Export');XLSX.writeFile(wb,'Prova_Paulista_Consolidada_Auditoria.xlsx');showMessage('Excel exportado com Detalhado, Resumo, Nível PP e Auditoria_Export.','success')}catch(e){console.error(e);showMessage('Erro ao exportar Excel: '+e.message,'error')}}
function wireDropzones(){qsa('.upload-card input[type="file"]').forEach((input,i)=>{input.addEventListener('change',()=>handleInput(input,i));const dz=input.closest('.dropzone');if(!dz)return;dz.addEventListener('dragover',e=>{e.preventDefault();dz.classList.add('dragover')});dz.addEventListener('dragleave',()=>dz.classList.remove('dragover'));dz.addEventListener('drop',e=>{e.preventDefault();dz.classList.remove('dragover');input.files=e.dataTransfer.files;handleInput(input,i)})})}
function wireButtons(){qsa('button').forEach(btn=>{const txt=(btn.textContent||'').toLowerCase();if(txt.includes('analisar'))btn.addEventListener('click',analyze);if(txt.includes('excel')||txt.includes('exportar'))btn.addEventListener('click',exportSummary)})}
document.addEventListener('DOMContentLoaded',()=>{wireDropzones();wireButtons();updateAll();showMessage('Sistema carregado. Envie .zip, .xlsx, .xls ou .csv e clique em Analisar.')});
