const STATUS=['Abaixo do Básico','Básico','Proficiente'];
const PESO={'ABAIXODOBASICO':1,'ABAIXO':1,'BASICO':2,'PROFICIENTE':3};
const state={files:[],saresp:[],diag:[],pp:[],dados:{saresp:[],diag:[],pp:[]},comparativo:[],auditoria:[]};
const charts={};
function qs(s){return document.querySelector(s)}
function qsa(s){return Array.from(document.querySelectorAll(s))}
function msg(t,type='info'){const e=qs('#msg');if(e){e.textContent=t;e.dataset.type=type}}
function norm(v){return String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}
function k(v){return norm(v).toUpperCase().replace(/[^A-Z0-9]/g,'')}
function num(v){if(v===null||v===undefined||v==='')return null;const n=Number(String(v).replace('%','').replace(',','.').trim());return Number.isFinite(n)?n:null}
function pctScale(n){if(n===null)return null;if(n<=1)return n*100;if(n<=10)return n*10;return n}
function esc(v){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function get(row,names){const map=Object.fromEntries(Object.keys(row||{}).map(x=>[k(x),x]));for(const n of names){const f=map[k(n)];if(f!==undefined)return row[f]}return ''}
function firstNum(row,names){for(const n of names){const v=num(get(row,[n]));if(v!==null)return v}return null}
function statusFromPercent(v){v=pctScale(v);if(v===null)return 'SEM DADO';if(v<50)return 'Abaixo do Básico';if(v<70)return 'Básico';return 'Proficiente'}
function cleanStatus(v,fallback){const s=k(v);if(PESO[s])return s==='ABAIXO'||s==='ABAIXODOBASICO'?'Abaixo do Básico':s==='BASICO'?'Básico':'Proficiente';return fallback!==undefined?statusFromPercent(fallback):'SEM DADO'}
function pesoStatus(s){return PESO[k(s)]||null}
function resultado(vals){const valid=vals.map(pesoStatus).filter(Boolean);if(!valid.length)return 'SEM DADO';if(valid.length===1)return 'MANTEVE';const a=valid[0],b=valid[valid.length-1];return b>a?'AVANÇOU':b<a?'REGREDIU':'MANTEVE'}
function geral(lp,mt){const vals=[lp,mt].filter(x=>x&&x!=='SEM DADO');if(!vals.length)return 'SEM DADO';if(vals.length===1)return vals[0];if(vals.includes('REGREDIU'))return 'REGREDIU';if(vals.includes('AVANÇOU'))return 'AVANÇOU';return 'MANTEVE'}
function turmaFromName(name){const m=String(name||'').toUpperCase().match(/\b([1-9][A-Z]|[1-9]\s*[A-Z]|[1-3][A-Z]\s*(EM|PC|EF)?)\b/);return m?m[0].replace(/\s+/g,' '):''}
function keyAluno(o){const ra=String(o.RA||'').trim();return ra&&ra!=='—'?'RA:'+k(ra):'NOME:'+k(o.Estudante)+'|TURMA:'+k(o.Turma)}
function loadScript(src,g){return new Promise((res,rej)=>{if(g&&window[g])return res(window[g]);const s=document.createElement('script');s.src=src;s.onload=()=>res(g?window[g]:true);s.onerror=()=>rej(new Error('Falha ao carregar '+src));document.head.appendChild(s)})}
function loadXLSX(){return loadScript('https://cdn.jsdelivr.net/npm/xlsx@0.18.5/dist/xlsx.full.min.js','XLSX')}
function loadJSZip(){return loadScript('https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js','JSZip')}
function parseCsv(txt){const sep=txt.includes(';')?';':',';const lines=txt.split(/\r?\n/).filter(x=>x.trim());const h=(lines.shift()||'').split(sep).map(x=>x.trim());return lines.map(l=>Object.fromEntries(l.split(sep).map((v,i)=>[h[i]||('Coluna '+(i+1)),v.trim()]))) }
async function readWorkbook(buf,name){const XLSX=await loadXLSX();const wb=XLSX.read(buf,{type:'array'});let rows=[];wb.SheetNames.forEach(sh=>XLSX.utils.sheet_to_json(wb.Sheets[sh],{defval:'',raw:false}).forEach(r=>{if(Object.values(r).some(v=>String(v??'').trim()))rows.push({...r,Arquivo:name,Aba:sh})}));return rows}
async function readFile(file){const e=(file.name.split('.').pop()||'').toLowerCase();if(e==='csv')return parseCsv(await file.text()).map(r=>({...r,Arquivo:file.name}));if(e==='xlsx'||e==='xls')return readWorkbook(await file.arrayBuffer(),file.name);if(e==='zip'){const JSZip=await loadJSZip();const zip=await JSZip.loadAsync(await file.arrayBuffer());let all=[];for(const ent of Object.values(zip.files).filter(z=>!z.dir)){const ex=(ent.name.split('.').pop()||'').toLowerCase();try{if(ex==='xlsx'||ex==='xls')all=all.concat(await readWorkbook(await ent.async('arraybuffer'),ent.name));if(ex==='csv')all=all.concat(parseCsv(await ent.async('text')).map(r=>({...r,Arquivo:ent.name})))}catch(err){state.auditoria.push({Aba:'Leitura',Contexto:ent.name,Tipo:'ERRO',Detalhe:err.message})}}return all}return []}
function tipoLinha(row){const name=k(row.Arquivo||'')+' '+k(row.Aba||'')+' '+Object.keys(row||{}).map(k).join(' ');if(name.includes('SARESP')||name.includes('LPT')||name.includes('REDEORIGEM')||name.includes('NOTAMEDIA'))return 'saresp';if(name.includes('DIAGNOST')||name.includes('APRENDEQUIV')||name.includes('PUBLICOALVO'))return 'diag';if(name.includes('PROVAPAULISTA')||name.includes('PROVAPAULIST')||name.includes('ACERTOS')||name.includes('PORT'))return 'pp';return 'pp'}
async function readSingleFiles(){state.dados.saresp=[];state.dados.diag=[];state.dados.pp=[];for(const f of state.files){const rows=await readFile(f);rows.forEach(r=>{const tipo=tipoLinha(r);if(tipo==='saresp')state.dados.saresp.push(calcSaresp(r));else if(tipo==='diag')state.dados.diag.push(calcDiag(r));else state.dados.pp.push(calcPP(r))})}}
function calcSaresp(row){const lp=firstNum(row,['LPT','LP','PORT','Português','Portugues','Língua Portuguesa','Lingua Portuguesa','Nota LP']);const mt=firstNum(row,['MAT','MT','Matemática','Matematica','Nota MAT']);return {Turma:get(row,['Turma','Classe'])||turmaFromName(row.Arquivo),Estudante:get(row,['Estudante','Aluno','Nome','Nome do Aluno']),RA:get(row,['RA','Código','Codigo'])||'—','LP SARESP':lp??'—','LP Status SARESP':cleanStatus(get(row,['Status LP SARESP','LP Status SARESP','Status LP']),lp),'MAT SARESP':mt??'—','MAT Status SARESP':cleanStatus(get(row,['Status MAT SARESP','MAT Status SARESP','Status MAT']),mt),Arquivo:row.Arquivo||''}}
function calcDiag(row){const lp=firstNum(row,['LP Aprend. Equiv','LP Aprendizagem Equivalente','LP AE','LP','Língua Portuguesa']);const mt=firstNum(row,['MAT Aprend. Equiv','MT Aprend. Equiv','MAT AE','MAT','Matemática']);return {Turma:get(row,['Turma','Classe'])||turmaFromName(row.Arquivo),Estudante:get(row,['Estudante','Aluno','Nome','Nome do Aluno']),RA:get(row,['RA','Código','Codigo'])||'—','Part. Diagnóstica':get(row,['(%) Participação','Participação','Participacao']),'LP Diagnóstica Aprend. Equiv':lp??'—','LP Status Diagnóstica':cleanStatus(get(row,['Status LP Diagnóstica','Status LP Diagnostica','LP Status Diagnóstica']),lp),'MAT Diagnóstica Aprend. Equiv':mt??'—','MAT Status Diagnóstica':cleanStatus(get(row,['Status MAT Diagnóstica','Status MAT Diagnostica','MAT Status Diagnóstica']),mt),Arquivo:row.Arquivo||''}}
function calcPP(row){const lp=firstNum(row,['PORT','LPT','LP','Português','Portugues','Lingua Portuguesa','(%) Acertos LP','% LP','LP %']);const mt=firstNum(row,['MAT','MT','Matemática','Matematica','(%) Acertos MAT','% MAT','MAT %']);return {Turma:get(row,['Turma','Classe'])||turmaFromName(row.Arquivo),Estudante:get(row,['Estudante','Aluno','Nome','Nome do Aluno']),RA:get(row,['RA','Código','Codigo'])||'—','Part. Prova Paulista':get(row,['(%) Participação','Participação','Participacao']),'LP Prova Paulista':lp??'—','LP Status Prova Paulista':cleanStatus(get(row,['Status LP Prova Paulista','LP Status Prova Paulista','Status LP']),lp),'MAT Prova Paulista':mt??'—','MAT Status Prova Paulista':cleanStatus(get(row,['Status MAT Prova Paulista','MAT Status Prova Paulista','Status MAT']),mt),Arquivo:row.Arquivo||''}}
function consolidate(){const map=new Map();function base(o){const id=keyAluno(o);if(!map.has(id))map.set(id,{Turma:o.Turma,Estudante:o.Estudante,RA:o.RA,'Part. Diagnóstica':'','LP SARESP':'','LP Status SARESP':'SEM DADO','LP Diagnóstica Aprend. Equiv':'','LP Status Diagnóstica':'SEM DADO','LP Prova Paulista':'','LP Status Prova Paulista':'SEM DADO','MAT SARESP':'','MAT Status SARESP':'SEM DADO','MAT Diagnóstica Aprend. Equiv':'','MAT Status Diagnóstica':'SEM DADO','MAT Prova Paulista':'','MAT Status Prova Paulista':'SEM DADO'});const r=map.get(id);r.Turma=r.Turma||o.Turma;r.Estudante=r.Estudante||o.Estudante;r.RA=r.RA||o.RA;return r}state.dados.saresp.forEach(o=>{if(o.Estudante||o.RA!=='—')Object.assign(base(o),o)});state.dados.diag.forEach(o=>{if(o.Estudante||o.RA!=='—')Object.assign(base(o),o)});state.dados.pp.forEach(o=>{if(o.Estudante||o.RA!=='—')Object.assign(base(o),o)});state.comparativo=[...map.values()].map(r=>{r['Status Final LP']=resultado([r['LP Status SARESP'],r['LP Status Diagnóstica'],r['LP Status Prova Paulista']]);r['Status Final MAT']=resultado([r['MAT Status SARESP'],r['MAT Status Diagnóstica'],r['MAT Status Prova Paulista']]);r['Status Final Geral 1º Bimestre']=geral(r['Status Final LP'],r['Status Final MAT']);return r}).sort((a,b)=>String(a.Turma).localeCompare(String(b.Turma))||String(a.Estudante).localeCompare(String(b.Estudante)))}
function counts(field){return ['AVANÇOU','MANTEVE','REGREDIU','SEM DADO'].map(s=>state.comparativo.filter(r=>r[field]===s).length)}
function avgStatus(field){const vals=state.comparativo.map(r=>pesoStatus(r[field])).filter(Boolean);return vals.length?Number((vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(2)):0}
function dist(field){return STATUS.map(s=>state.comparativo.filter(r=>r[field]===s).length).concat([state.comparativo.filter(r=>!r[field]||r[field]==='SEM DADO').length])}
function destroyCharts(){Object.values(charts).forEach(c=>{if(c)c.destroy()})}
function makeChart(id,type,data,options){const el=document.getElementById(id);if(!el||typeof Chart==='undefined')return null;return new Chart(el,{type,data,options})}
function renderCharts(){if(!state.comparativo.length||typeof Chart==='undefined')return;destroyCharts();const c=counts('Status Final Geral 1º Bimestre');charts.geral=makeChart('chartStatusGeral','doughnut',{labels:['AVANÇOU','MANTEVE','REGREDIU','SEM DADO'],datasets:[{data:c,backgroundColor:['#16a34a','#facc15','#dc2626','#94a3b8']}]},{plugins:{legend:{position:'bottom'}}});charts.curva=makeChart('chartCurvaEvolucao','line',{labels:['SARESP','Diagnóstica','Prova Paulista'],datasets:[{label:'LP',data:[avgStatus('LP Status SARESP'),avgStatus('LP Status Diagnóstica'),avgStatus('LP Status Prova Paulista')],borderColor:'#7c3aed',backgroundColor:'#7c3aed',tension:.35},{label:'MAT',data:[avgStatus('MAT Status SARESP'),avgStatus('MAT Status Diagnóstica'),avgStatus('MAT Status Prova Paulista')],borderColor:'#16a34a',backgroundColor:'#16a34a',tension:.35}]},{scales:{y:{min:1,max:3,ticks:{stepSize:1,callback:v=>v===1?'Abaixo':v===2?'Básico':v===3?'Proficiente':v}}}});const colors=['#dc2626','#facc15','#16a34a','#94a3b8'];const labels=['Abaixo do Básico','Básico','Proficiente','Sem dado'];function stacked(id,a,b,c){return makeChart(id,'bar',{labels:['SARESP','Diagnóstica','Prova Paulista'],datasets:labels.map((l,i)=>({label:l,data:[a[i],b[i],c[i]],backgroundColor:colors[i]}))},{scales:{x:{stacked:true},y:{stacked:true}}})}charts.lp=stacked('chartLP',dist('LP Status SARESP'),dist('LP Status Diagnóstica'),dist('LP Status Prova Paulista'));charts.mat=stacked('chartMAT',dist('MAT Status SARESP'),dist('MAT Status Diagnóstica'),dist('MAT Status Prova Paulista'));const turmas=[...new Set(state.comparativo.map(r=>r.Turma).filter(Boolean))].slice(0,12);charts.turmas=makeChart('chartTurmas','bar',{labels:turmas,datasets:[{label:'AVANÇOU',data:turmas.map(t=>state.comparativo.filter(r=>r.Turma===t&&r['Status Final Geral 1º Bimestre']==='AVANÇOU').length),backgroundColor:'#16a34a'},{label:'MANTEVE',data:turmas.map(t=>state.comparativo.filter(r=>r.Turma===t&&r['Status Final Geral 1º Bimestre']==='MANTEVE').length),backgroundColor:'#facc15'},{label:'REGREDIU',data:turmas.map(t=>state.comparativo.filter(r=>r.Turma===t&&r['Status Final Geral 1º Bimestre']==='REGREDIU').length),backgroundColor:'#dc2626'}]},{scales:{x:{stacked:true},y:{stacked:true}}})}
function updateButtons(){const total=state.files.length;qsa('button').forEach(b=>{const t=b.textContent.toLowerCase();if(t.includes('analisar')){b.disabled=total===0;b.textContent='Analisar ('+total+')'}if(t.includes('excel')||t.includes('exportar'))b.disabled=total===0})}
function updateCards(){const card=qs('.upload-card');if(!card)return;const sp=card.querySelector('.card-head span');if(sp)sp.textContent=state.files.length+' arquivo'+(state.files.length===1?'':'s')}
function render(){updateCards();updateButtons();const box=qs('.notice');if(!box)return;if(!state.comparativo.length){box.innerHTML='Envie todos os arquivos no <b>campo único</b> e clique em <b>Analisar</b>. O sistema separa SARESP, Diagnóstica e Prova Paulista automaticamente.';return}const c=counts('Status Final Geral 1º Bimestre');const rows=state.comparativo.slice(0,15).map(r=>'<tr><td>'+esc(r.Turma)+'</td><td>'+esc(r.Estudante)+'</td><td>'+r['Status Final LP']+'</td><td>'+r['Status Final MAT']+'</td><td><b>'+r['Status Final Geral 1º Bimestre']+'</b></td></tr>').join('');box.innerHTML='<div class="analysis-grid"><article><span>Estudantes</span><strong>'+state.comparativo.length+'</strong></article><article><span>AVANÇOU</span><strong>'+c[0]+'</strong></article><article><span>MANTEVE</span><strong>'+c[1]+'</strong></article><article><span>REGREDIU</span><strong>'+c[2]+'</strong></article></div><div class="analysis-card"><h3>Comparativo por estudante</h3><table class="analysis-table"><thead><tr><th>Turma</th><th>Estudante</th><th>Final LP</th><th>Final MAT</th><th>Geral</th></tr></thead><tbody>'+rows+'</tbody></table></div>';const cards=qsa('.dashboard-preview article strong');if(cards[0])cards[0].textContent=state.comparativo.length;if(cards[1])cards[1].textContent=new Set(state.comparativo.map(r=>r.Turma)).size;if(cards[2])cards[2].textContent=c[0];if(cards[3])cards[3].textContent=c[3];renderCharts();if(typeof renderProficiency==='function')renderProficiency()}
async function analyze(){try{msg('Lendo campo único, separando bases e gerando análise...');await readSingleFiles();consolidate();render();msg('Análise concluída: '+state.comparativo.length+' estudante(s). SARESP: '+state.dados.saresp.length+', Diagnóstica: '+state.dados.diag.length+', Prova Paulista: '+state.dados.pp.length+'.','success')}catch(e){console.error(e);msg('Erro ao analisar: '+e.message,'error')}}
async function exportExcel(){if(!state.comparativo.length)await analyze();const XLSX=await loadXLSX();const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet([{Titulo:'PAINEL CONSOLIDADO DA UNIDADE'},{Subtitulo:'Consolidado seguindo a ordem: SARESP → Diagnóstica → Prova Paulista'},{Status:'AVANÇOU',Geral:counts('Status Final Geral 1º Bimestre')[0]},{Status:'MANTEVE',Geral:counts('Status Final Geral 1º Bimestre')[1]},{Status:'REGREDIU',Geral:counts('Status Final Geral 1º Bimestre')[2]},{Status:'SEM DADO',Geral:counts('Status Final Geral 1º Bimestre')[3]}]),'Painel');[...new Set(state.comparativo.map(r=>r.Turma||'SEM TURMA'))].forEach(t=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.comparativo.filter(r=>(r.Turma||'SEM TURMA')===t)),('COMPARATIVO - '+t).slice(0,31)));XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.dados.saresp),'Dados SARESP');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.dados.diag),'Dados Diagnóstica');XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(state.dados.pp),'Dados Prova Paulista');if(typeof profRowsForExport==='function')XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(profRowsForExport()),'Níveis Proficiência');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Parâmetro','Descrição'],['Campo de upload','Único'],['Separação','Automática por nome/colunas'],['Ordem','SARESP → Diagnóstica → Prova Paulista'],['Hierarquia','Abaixo do Básico=1; Básico=2; Proficiente=3'],['Comparação','Final maior=AVANÇOU; igual=MANTEVE; menor=REGREDIU']]),'Parâmetros');XLSX.writeFile(wb,'Consolidacao_Educacional_Oficial.xlsx');msg('Excel gerado.','success')}
function handleInput(input){state.files=Array.from(input.files||[]);state.comparativo=[];state.dados={saresp:[],diag:[],pp:[]};destroyCharts();render();msg(state.files.length+' arquivo(s) carregado(s) no campo único.')}
function wire(){qsa('input[type="file"]').forEach(input=>input.addEventListener('change',()=>handleInput(input)));qsa('button').forEach(b=>{const t=b.textContent.toLowerCase();if(t.includes('analisar'))b.addEventListener('click',analyze);if(t.includes('excel')||t.includes('exportar'))b.addEventListener('click',exportExcel)});render();msg('Sistema carregado. Envie todos os arquivos no campo único e clique em Analisar.')}
document.addEventListener('DOMContentLoaded',wire);
