const DATA={pp:[],saresp:[],diag:[]};
const CHARTS={};
const DISC={LP:['LP','LPT','PORT','PORTUGUES','LINGUA PORTUGUESA'],MAT:['MAT','MT','MATEMATICA'],CIE:['CIE','CIENCIAS'],BIO:['BIO','BIOLOGIA'],HIS:['HIS','HISTORIA'],GEO:['GEO','GEOGRAFIA'],ING:['ING','INGLES'],ART:['ART','ARTE'],EDF:['ED FISICA','EDUCACAO FISICA'],FIS:['FIS','FISICA'],QUI:['QUI','QUIMICA'],FIL:['FIL','FILOSOFIA'],SOC:['SOC','SOCIOLOGIA']};
const LABEL={LP:'Língua Portuguesa',MAT:'Matemática',CIE:'Ciências',BIO:'Biologia',HIS:'História',GEO:'Geografia',ING:'Inglês',ART:'Arte',EDF:'Educação Física',FIS:'Física',QUI:'Química',FIL:'Filosofia',SOC:'Sociologia'};
function q(s){return document.querySelector(s)}function qa(s){return [...document.querySelectorAll(s)]}
function clean(s){return String(s??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim()}function key(s){return clean(s).toUpperCase().replace(/[^A-Z0-9]/g,'')}function esc(s){return String(s??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function num(v){if(v===null||v===undefined||v==='')return null;let n=Number(String(v).replace('%','').replace(',','.').trim());return Number.isFinite(n)?n:null}function pct(v){if(v===null)return null;if(v<=1)return v*100;if(v<=10)return v*10;return v}
function status(v){v=pct(v);if(v===null)return 'SEM DADO';if(v<50)return 'Abaixo do Básico';if(v<70)return 'Básico';return 'Proficiente'}
function statusText(s){let t=key(s);if(t.includes('ABAIXO'))return 'Abaixo do Básico';if(t.includes('BASICO'))return 'Básico';if(t.includes('PROFICIENTE')||t.includes('AVANCADO')||t.includes('DOMINIO'))return 'Proficiente';return 'SEM DADO'}
function peso(n){return {'Abaixo do Básico':1,'Básico':2,'Proficiente':3}[n]||0}function evolui(a,b){if(!peso(a)||!peso(b))return 'SEM DADO';if(peso(b)>peso(a))return 'AVANÇOU';if(peso(b)<peso(a))return 'REGREDIU';return 'MANTEVE'}
function get(row,names){let map=Object.fromEntries(Object.keys(row).map(k=>[key(k),k]));for(const n of names){let f=map[key(n)];if(f!==undefined)return row[f]}return ''}function first(row,names){for(const n of names){let x=num(get(row,[n]));if(x!==null)return x}return null}
function headerScore(a){let t=a.map(clean).join(' ').toUpperCase();return ['RA','ALUNO','ESTUDANTE','NOME','TURMA','CLASSE','SERIE','ANO','LP','LPT','PORT','MAT','BIO','HISTORIA','GEOGRAFIA','ACERTOS','PROFICIENCIA','NIVEL'].filter(w=>t.includes(w)).length}
function headers(a){let seen={};return a.map((x,i)=>{let h=clean(x)||'Coluna '+(i+1);if(seen[h]){seen[h]++;h+=' '+seen[h]}else seen[h]=1;return h})}
function aoaRows(aoa,file,sheet=''){let best=0,score=-1;aoa.slice(0,30).forEach((r,i)=>{let s=headerScore(r);if(s>score){score=s;best=i}});let h=headers(aoa[best]||[]);let out=[];for(let i=best+1;i<aoa.length;i++){let line=aoa[i]||[];if(!line.some(x=>String(x??'').trim()))continue;let o={Arquivo:file,Aba:sheet};h.forEach((x,j)=>o[x]=line[j]??'');out.push(o)}return out}
async function readOne(file){let ext=file.name.split('.').pop().toLowerCase();if(ext==='csv'){let txt=await file.text();let sep=txt.includes(';')?';':',';return aoaRows(txt.split(/\r?\n/).filter(x=>x.trim()).map(x=>x.split(sep)),file.name)}if(ext==='xlsx'||ext==='xls'){return readWorkbook(await file.arrayBuffer(),file.name)}if(ext==='zip'){let out=[];let zip=await JSZip.loadAsync(await file.arrayBuffer());for(const ent of Object.values(zip.files).filter(z=>!z.dir)){let e=ent.name.split('.').pop().toLowerCase();if(e==='xlsx'||e==='xls')out=out.concat(readWorkbook(await ent.async('arraybuffer'),ent.name));if(e==='csv'){let txt=await ent.async('text');let sep=txt.includes(';')?';':',';out=out.concat(aoaRows(txt.split(/\r?\n/).filter(x=>x.trim()).map(x=>x.split(sep)),ent.name))}}return out}return[]}
function readWorkbook(buf,name){let wb=XLSX.read(buf,{type:'array'});let out=[];wb.SheetNames.forEach(sh=>{let aoa=XLSX.utils.sheet_to_json(wb.Sheets[sh],{header:1,defval:'',raw:false});out=out.concat(aoaRows(aoa,name,sh))});return out}
function invalidName(n){let t=key(n);return !t||['FILTROSAPLICADOS','COMPONENTE','GERALLPMAT','LINGUAPORTUGUESA','LP','MAT','MATEMATICA','SEMDADO','TOTAL','TOTAIS'].includes(t)||t.startsWith('FILTROS')}
function ano(t){let s=String(t||'').toUpperCase();let m=s.match(/\b([6-9])\s*(A|B|C|D|E|ANO|º|°)?\b/);if(m)return m[1]+'º Ano';m=s.match(/\b([1-3])\s*(A|B|C|D|E|EM|SERIE|ª)?\b/);if(m)return m[1]+'ª Série EM';return 'Sem Ano/Série'}
function parseRow(row,base){let estudante=get(row,['Estudante','Aluno','Nome','Nome do Aluno','NM_ALUNO','NM_ESTUDANTE']);let ra=get(row,['RA','Codigo','Código','Código do Aluno','CD_ALUNO','ID'])||'—';let turma=get(row,['Turma','Classe','Ano/Série','Ano Serie','Série','Serie','NM_TURMA'])||'SEM TURMA';if(invalidName(estudante)&&ra==='—')return null;let discs=base==='diag'?['LP','MAT']:Object.keys(DISC);let results=[];discs.forEach(d=>{let aliases=DISC[d],names=[];aliases.forEach(a=>names.push(a,a+' %','% '+a,'ACERTOS '+a,'NOTA '+a,'PERCENTUAL '+a,'PROFICIENCIA '+a));let val=first(row,names);let st=get(row,aliases.flatMap(a=>['STATUS '+a,a+' STATUS','NIVEL '+a,a+' NIVEL','PROFICIENCIA '+a]));let nivel=st?statusText(st):status(val);if(nivel!=='SEM DADO'||val!==null)results.push({base,avaliacao:base==='pp'?'Prova Paulista':base==='saresp'?'SARESP':'Diagnóstica',ano:ano(turma),turma,estudante,ra,disciplina:LABEL[d],valor:val??'—',nivel})});return results}
async function analyze(base){let files=[...q('#file-'+base).files];q('#msg-'+base).textContent='Lendo '+files.length+' arquivo(s)...';let rows=[];for(const f of files)rows=rows.concat(await readOne(f));let parsed=[];rows.forEach(r=>{let p=parseRow(r,base);if(p)parsed=parsed.concat(p)});DATA[base]=parsed;renderBase(base);q('#msg-'+base).textContent='Análise concluída: '+parsed.length+' registro(s).'}
function counts(rows){return ['Abaixo do Básico','Básico','Proficiente','SEM DADO'].map(n=>rows.filter(r=>r.nivel===n).length)}
function renderChart(id,rows){if(!window.Chart)return;let old=CHARTS[id];if(old)old.destroy();let ctx=q('#'+id);if(!ctx)return;CHARTS[id]=new Chart(ctx,{type:'doughnut',data:{labels:['Abaixo','Básico','Proficiente','Sem dado'],datasets:[{data:counts(rows),backgroundColor:['#dc2626','#f59e0b','#16a34a','#94a3b8']}]},options:{plugins:{legend:{position:'bottom'}}}})}
function renderBase(base){let rows=DATA[base],out=q('#out-'+base);if(!rows.length){out.innerHTML='<div class="empty">Nenhum estudante válido encontrado.</div>';return}let below=rows.filter(r=>r.nivel==='Abaixo do Básico'),basic=rows.filter(r=>r.nivel==='Básico'),prof=rows.filter(r=>r.nivel==='Proficiente');let cid='chart-'+base;let html='<div class="grid"><div class="card"><span>Registros</span><strong>'+rows.length+'</strong></div><div class="card"><span>Abaixo</span><strong>'+below.length+'</strong></div><div class="card"><span>Básico</span><strong>'+basic.length+'</strong></div><div class="card"><span>Proficiente</span><strong>'+prof.length+'</strong></div></div><div class="section"><div class="section-title">Distribuição por nível</div><div class="section-body"><canvas id="'+cid+'" height="120"></canvas></div></div>';let groups={};rows.forEach(r=>{let kk=r.ano+'||'+r.turma+'||'+r.disciplina;if(!groups[kk])groups[kk]=[];groups[kk].push(r)});Object.entries(groups).sort().forEach(([kk,list])=>{let[a,t,d]=kk.split('||');html+='<div class="section"><div class="section-title">'+esc(a)+' - '+esc(t)+' - '+esc(d)+'</div><div class="section-body">';['Abaixo do Básico','Básico','Proficiente','SEM DADO'].forEach(n=>{let l=list.filter(x=>x.nivel===n);if(l.length)html+='<h4>'+n+'</h4>'+l.map(x=>'<span class="chip">'+esc(x.estudante)+' <small>'+esc(x.ra)+'</small></span>').join('')});html+='</div></div>'});html+='<div class="section"><div class="section-title">Alunos Abaixo do Básico</div><div class="section-body"><table class="tbl"><thead><tr><th>Ano/Série</th><th>Turma</th><th>Estudante</th><th>RA</th><th>Disciplina</th><th>Valor</th></tr></thead><tbody>'+below.map(r=>'<tr><td>'+esc(r.ano)+'</td><td>'+esc(r.turma)+'</td><td>'+esc(r.estudante)+'</td><td>'+esc(r.ra)+'</td><td>'+esc(r.disciplina)+'</td><td>'+esc(r.valor)+'</td></tr>').join('')+'</tbody></table></div></div>';out.innerHTML=html;setTimeout(()=>renderChart(cid,rows),0)}
function matchKey(r){return key(r.ra&&r.ra!=='—'?r.ra:r.estudante+' '+r.turma)+'|'+key(r.disciplina)}
function compareSarespPP(){let pp=new Map(DATA.pp.map(r=>[matchKey(r),r]));let out=[];DATA.saresp.forEach(s=>{let p=pp.get(matchKey(s));out.push({ano:s.ano,turma:s.turma,estudante:s.estudante,ra:s.ra,disciplina:s.disciplina,saresp:s.nivel,provaPaulista:p?p.nivel:'SEM DADO',evolucao:evolui(s.nivel,p?p.nivel:'SEM DADO')})});return out}
function consolidate(){let all=[...DATA.pp,...DATA.saresp,...DATA.diag];if(!all.length){q('#out-cons').innerHTML='<div class="empty">Nenhuma avaliação analisada.</div>';return}let below=all.filter(r=>r.nivel==='Abaixo do Básico');let comp=compareSarespPP();let rowsComp=comp.slice(0,200).map(r=>'<tr><td>'+esc(r.ano)+'</td><td>'+esc(r.turma)+'</td><td>'+esc(r.estudante)+'</td><td>'+esc(r.disciplina)+'</td><td>'+r.saresp+'</td><td>'+r.provaPaulista+'</td><td><b>'+r.evolucao+'</b></td></tr>').join('');q('#out-cons').innerHTML='<div class="grid"><div class="card"><span>Total</span><strong>'+all.length+'</strong></div><div class="card"><span>PP</span><strong>'+DATA.pp.length+'</strong></div><div class="card"><span>SARESP</span><strong>'+DATA.saresp.length+'</strong></div><div class="card"><span>Diagnóstica</span><strong>'+DATA.diag.length+'</strong></div></div><div class="section"><div class="section-title">Comparativo SARESP x Prova Paulista</div><div class="section-body"><table class="tbl"><thead><tr><th>Ano/Série</th><th>Turma</th><th>Estudante</th><th>Disciplina</th><th>SARESP</th><th>Prova Paulista</th><th>Evolução</th></tr></thead><tbody>'+rowsComp+'</tbody></table></div></div><div class="section"><div class="section-title">Todos abaixo do básico</div><div class="section-body"><table class="tbl"><thead><tr><th>Avaliação</th><th>Ano/Série</th><th>Turma</th><th>Estudante</th><th>Disciplina</th></tr></thead><tbody>'+below.map(r=>'<tr><td>'+r.avaliacao+'</td><td>'+esc(r.ano)+'</td><td>'+esc(r.turma)+'</td><td>'+esc(r.estudante)+'</td><td>'+esc(r.disciplina)+'</td></tr>').join('')+'</tbody></table></div></div>';q('#msg-cons').textContent='Consolidado gerado.'}
function exportX(){let wb=XLSX.utils.book_new();[['Prova Paulista',DATA.pp],['SARESP',DATA.saresp],['Diagnóstica',DATA.diag],['Abaixo do Básico',[...DATA.pp,...DATA.saresp,...DATA.diag].filter(r=>r.nivel==='Abaixo do Básico')],['Comparativo SARESP x PP',compareSarespPP()],['Dados Brutos',[...DATA.pp,...DATA.saresp,...DATA.diag]]].forEach(([n,d])=>XLSX.utils.book_append_sheet(wb,XLSX.utils.json_to_sheet(d),n.slice(0,31)));XLSX.writeFile(wb,'relatorios_ure_sat.xlsx')}
qa('.tab-btn').forEach(b=>b.onclick=()=>{qa('.tab-btn').forEach(x=>x.classList.remove('active'));qa('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');q('#'+b.dataset.tab).classList.add('active')});qa('[data-analyze]').forEach(b=>b.onclick=()=>analyze(b.dataset.analyze));q('#btn-cons').onclick=consolidate;q('#btn-xlsx').onclick=exportX;let top=q('#btn-xlsx-top');if(top)top.onclick=exportX;